language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

before_script:
  - composer install

script:
  - ./vendor/bin/phpunit

  # phpcs only on latest PHP
  - if [[ $TRAVIS_PHP_VERSION = '5.6' ]]; then ./vendor/bin/phpcs --standard=PSR2 src; fi
  - if [[ $TRAVIS_PHP_VERSION = '5.6' ]]; then ./vendor/bin/phpcs --standard=PSR2 tests; fi

matrix:
  allow_failures:
   - php: 7
